default: &default
  adapter: sqlite3
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3


production:
  adapter: postgresql
  encoding: unicode
  database: pets_rknh
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 2
  username: cindy
  password: <%= ENV['DATABASE_PASSWORD'] %>