default: &default
  adapter: sqlite3
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3


production:
  adapter: postgresql
  encoding: unicode
  database: pets_rknh
  host: dpg-cg39p0l269v3bp94pap0-a.oregon-postgres.render.com
  pool: 2
  username: cindy
  password: 3s5ixJKXcqOfA8mfAzqSLK3klHxoZAb6